working_dir : /home/shiheyuan/linux
filter :
  branch : master
  restrict :
    commit_count : -1  # commit_count limit or -1 to ignore limit
    # precise date or -1 to ignore date bound
    from_date : 2010-05-01
    to_date : 2018-05-01
  key_words :
    first :
      - bug
      - fix
      - check
      - issue
      - mistake
      - incorrect
      - fault
      - defect
      - error
    second :
      - CVE-20
  LOC : 20
  NOF : 3
  file_name :
    - test
    - news
    - contribute
  ignore_case : True
output :
  dir : /home/shiheyuan/workspace/linux-10-18-db
  file_name : report.db
  # diff_xxx fields denote whether outputting diff patches in corresponding folders
  diff_mid : False # whether outputting middle result
  diff_result : False  # whether outputting final result
